### ISSUE TITLE
Eccezione in assenza di permessi cookie

### ISSUE THREAD

**Issue by nemobis** [synapta/maschera-inserimento-wikidata#3]
Tornando da https://autorizzazioni.wikilovesmonuments.it/login e meta.wikimedia.org dopo aver autorizzato l'applicazione OAuth, se non sono attivati i cookie si incontra un'eccezione.

Bisognerebbe invece dare un messaggio di errore comprensibile.

```
Error: failed to find request token in session
    at Strategy.OAuthStrategy.authenticate (/var/www/nginx/maschera-inserimento-wikidata/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:124:54)
    at attempt (/var/www/nginx/maschera-inserimento-wikidata/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/var/www/nginx/maschera-inserimento-wikidata/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at Layer.handle [as handle_request] (/var/www/nginx/maschera-inserimento-wikidata/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/nginx/maschera-inserimento-wikidata/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/nginx/maschera-inserimento-wikidata/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/nginx/maschera-inserimento-wikidata/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/nginx/maschera-inserimento-wikidata/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/nginx/maschera-inserimento-wikidata/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/nginx/maschera-inserimento-wikidata/node_modules/express/lib/router/index.js:275:10)
```

**Comment by diegmonti** [comment]
Risolto da 21d9db8033714655460466b03c58e87f9b231647. Ora viene effettuato un reindirizzamento verso `/login?error`.
